Numpy Practice Questions
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0


	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [12]:
#Numpy Q1
import numpy as np
np.random.seed(42)  # seed for reproducibility

A = np.random.randint(10, size=10)  
B = np.random.randint(10, size=10) 

horizontal = np.hstack([A,B])
vertical = np.vstack([A,B])

print(A)
print(B)
print(horizontal)
print(vertical)

[6 3 7 4 6 9 2 6 7 4]
[3 7 7 2 5 4 1 7 5 1]
[6 3 7 4 6 9 2 6 7 4 3 7 7 2 5 4 1 7 5 1]
[[6 3 7 4 6 9 2 6 7 4]
 [3 7 7 2 5 4 1 7 5 1]]


In [13]:
#Numpy Q2
print(np.intersect1d(A,B))

[2 3 4 7]


In [8]:
vertical

array([[6, 3, 7, 4, 6, 9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5, 4, 1, 7, 5, 1]])

In [22]:
#Numpy Q3
def extractRange(arr,low,high):
    return arr[np.where((arr >= low) & (arr <= high))]

print(extractRange(A,5,10))

[6 7 6 9 6 7]


In [28]:
#Numpy Q4
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filter = iris_2d[np.where((iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0))]
print(filter)


[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [96]:
#Pandas Questions
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

#Q1
df_q1 = df.iloc[::20][["Manufacturer","Model","Type"]]

#Q2
df.loc[df["Min.Price"].isnull(),"Min.Price"] = round(df["Min.Price"].mean(),1)
df.loc[df["Max.Price"].isnull(),"Max.Price"] = round(df["Max.Price"].mean(),1)

#Q3
df_q3 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df_q3.loc[df_q3.apply(lambda row: row.name if row.sum() >= 100 else None,axis=1).dropna()]


0   1   2   3
3   32  32  39  33
8   32  23  16  36
9   18  24  24  35
10  19  37  22  28
11  16  26  29  38